[workspace]
resolver = "2"
members = [
    "examples/*",
    "claims-core",
    "claims-schema",
    "app-claims-service",
    "app-claims-version-service"
]

default-members = [
    "claims-core",
    "claims-schema",
    "app-*"
]