# example taken from:
# https://github.com/debezium/debezium-examples/blob/main/auditlog/docker-compose.yaml

version: '3.8'
services:
  zookeeper:
    container_name: kd-zookeeper
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - kd-demo
  kafka:
    container_name: kd-kafka
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      # What is this for????
      # For local development of auditlog-enricher
#      - ADVERTISED_HOST_NAME=192.168.1.6
      - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=250
    networks:
      - kd-demo
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    container_name: kd-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=claimsdb
    networks:
      - kd-demo
networks:
  kd-demo:
    name: kd-demo