# example taken from:
# https://github.com/debezium/debezium-examples/blob/main/auditlog/docker-compose.yaml

version: '3.8'
services:
  zookeeper:
    container_name: kd-zookeeper
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - "52181:2181"
      - "52888:2888"
      - "53888:3888"
    networks:
      - kd-demo
  kafka:
    container_name: kd-kafka
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - "59092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:59092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:59092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks:
      - kd-demo
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    container_name: kd-postgres
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_user
      - POSTGRES_DB=claimsdb
    volumes:
#      - conf/postgresdata:/var/lib/postgresql/data
      - ./conf/db-init:/docker-entrypoint-initdb.d
    networks:
      - kd-demo
networks:
  kd-demo:
    name: kd-demo