server:
  port: 58080
db:
  url: postgres://postgres_user:postgres_user@localhost:55432/claimsdb
schema_registry:
  url: http://localhost:58003
graceful-shutdown: 5
log:
  level:
    root: warn
    directives:
      - namespace: app_claims_service
        level: debug
      - namespace: sqlx::query
        level: debug